name: Trendyol Web Test Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
        
    - name: Run Tests
      run: mvn clean test -Dtest=runner
      continue-on-error: true
      
    - name: Archive Cucumber Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cucumber-reports
        path: Reports/CucumberReport/Reports.html
        retention-days: 30
        
    - name: Archive TestNG Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: testng-reports
        path: |
          target/surefire-reports/emailable-report.html
          target/surefire-reports/index.html
        retention-days: 30