name: Trendyol Web Test Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
        
    - name: Run Tests
      run: |
        export DISPLAY=:99
        sudo Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        mvn clean test -Dtest=runner \
        -Dwebdriver.chrome.args="--headless=new --no-sandbox --disable-dev-shm-usage --window-size=1920,1080" \
        -Dwebdriver.timeouts.implicitlywait=10000 \
        -Dwebdriver.timeouts.pageLoadTimeout=30000
      continue-on-error: true
      
    - name: Archive Cucumber Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cucumber-reports
        path: Reports/CucumberReport/Reports.html
        retention-days: 30